import type { Product } from "../types";

export const demoProducts: Product[] = [
  {
    id: "prod_1",
    name: "Hand-Woven Basket",
    slug: "hand-woven-basket",
    description:
      "A beautiful hand-woven basket, perfect for home decor or storage. Made with natural fibers by local artisans in Rwanda.",
    price: "25000",
    currency: "RWF",
    stock: 15,
    imageUrl: "https://picsum.photos/seed/prod_1/400/400",
    isActive: true,
    rating: 4.5,
    categoryId: "cat_1",
    category: { id: "cat_1", name: "Handicrafts", slug: "handicrafts" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_2",
    name: "Imigongo Wall Art",
    slug: "imigongo-wall-art",
    description:
      "Traditional Rwandan Imigongo art piece. This black and white geometric design will be a stunning addition to any wall.",
    price: "75000",
    currency: "RWF",
    stock: 5,
    imageUrl: "https://picsum.photos/seed/prod_2/400/400",
    isActive: true,
    rating: 4.8,
    categoryId: "cat_1",
    category: { id: "cat_1", name: "Handicrafts", slug: "handicrafts" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_3",
    name: "Kitenge Fabric Dress",
    slug: "kitenge-fabric-dress",
    description:
      "A vibrant and stylish dress made from authentic Kitenge fabric. Perfect for any occasion.",
    price: "45000",
    currency: "RWF",
    stock: 20,
    imageUrl: "https://picsum.photos/seed/prod_3/400/400",
    isActive: true,
    rating: 4.2,
    categoryId: "cat_2",
    category: { id: "cat_2", name: "Fashion", slug: "fashion" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_4",
    name: "Gorilla Trekking Permit",
    slug: "gorilla-trekking-permit",
    description:
      "A once-in-a-lifetime experience to see the mountain gorillas of Volcanoes National Park.",
    price: "1500000",
    currency: "RWF",
    stock: 10,
    imageUrl: "https://picsum.photos/seed/prod_4/400/400",
    isActive: true,
    rating: 5.0,
    categoryId: "cat_3",
    category: { id: "cat_3", name: "Tourism", slug: "tourism" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "prod_5",
    name: "Rwandan Coffee Beans",
    slug: "rwandan-coffee-beans",
    description:
      "Premium, single-origin Arabica coffee beans from the hills of Rwanda. Full-bodied with notes of citrus and chocolate.",
    price: "12000",
    currency: "RWF",
    stock: 50,
    imageUrl: null, // This one will use the picsum.photos fallback
    isActive: true,
    rating: 4.9,
    categoryId: "cat_4",
    category: { id: "cat_4", name: "Groceries", slug: "groceries" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
